### ISSUE TITLE
Page navigation in user search uses current search text rather than initial search value

### ISSUE THREAD

**Issue by ghost** [Anaminus/roblox-bug-tracker#500]
So, while I was scanning around on ROBLOX, I saw that you can see all of the people in the WHOLE ROBLOX database, which is pretty cool.

How to do this:
1. Go on People and search "test" or any keyword
2. Press enter and then clear out the search box
3. Go to the second page and you will see all of the users shown in the database.

TheNomad was the first user on the ROBLOX database.

Thank you for your time,
HappyRocketwheel

**Comment by Squidcod** [comment]
appears to have been fixed or deprecated.
If there are any other repros please throw em up here.

**Comment by Anaminus** [comment]
The empty query bug appears to be fixed. Though the page navigation is still a problem.

1. Search for a user with the keyword "alice" (e.g. [alice](http://www.roblox.com/search/users?keyword=alice))
2. In the user search bar (not in the topbar), replace "alice" with "bob", but do not search.
3. At the bottom of the page, navigate to the next page.
4. Observe that you are now on the second page for the "bob" keyword, rather than "alice".

**Comment by Squidcod** [comment]
Entered internally.
thanks.
