### ISSUE TITLE
409 Security errors with loading ROBLOX Crossroads

### ISSUE THREAD

**Issue by Nitro509** [Anaminus/roblox-bug-tracker#662]
I was creating a map which required the rocket launcher, so I decided to export the launcher from the place Crossroads from the user ROBLOX (which I hope we are all familiar with). Before I could though, errors for every BrickBattle tool showed up, a error that says: "httpGet http://www.roblox.com/asset/?id=1014654 failed. Trying again. Error: HTTP 409  (HTTP/1.1 409 User is not authorized to access Asset.).  Elapsed time: 0.291108. The LinkedSource name may have changed or been removed."

I tried opening ports 49152 - 65535 on my router but that seemed to not work. I tried running ROBLOX Studio in Administrator mode but I had another problem with Studio not even opening up afterwards. I had to reinstall Studio. 

Obviously the LinkedSource may have been changed or even been removed, but however Crossroads when playing in Multiplayer mode seems to work perfectly fine with loading the items. 

My reasoning is behind the possibility of a bug in the new HTTP API once you load ROBLOX Studio, but I am not sure, and keeping it from loading assets properly. This leads to another point that the LinkedSource could not have been either changed or removed. By the looks of it in the Settings... option in the "File" toolbar, I couldn't find a way to use a older version of the HTTP API or not.

**Comment by SNCPlay42** [comment]
I believe this is an unfortunate but foreseen side-effect of an intentional change to how LinkedSource works to make it available to developers.

**Comment by einsteinK** [comment]
For security reasons with the new LinkedSource stuff @SNCPlay42  mentioned, Lua assets can
only be loaded by the owner (or in the place owned by the owner).
If you want to use those scripts, you'll probably have to check the Free Models for copies.

**Comment by Nitro509** [comment]
Alright, thanks for the heads up einstein and SNC. 
I haven't played ROBLOX in a long time so I was unaware of these changes to the system.

**Comment by einsteinK** [comment]
These changes are very recent, less than a month if I recall correctly.

**Comment by dignatoff** [comment]
We are working on a change (to be released soon) that will make all scripts published under the roblox account public access, which should resolve this issue.

**Comment by Nitro509** [comment]
Thank you for the response.

**Comment by xMRENDERMAN** [comment]
Yeah, Still getting the HTTP 403 (HTTP/1.1 403 Asset is not trusted for this place) error in studio..
